services:
  - type: web
    name: mariah-backend
    runtime: node
    rootDir: backend
    buildCommand: rm -rf node_modules && npm install --include=dev && npm run build
    startCommand: npm start
